_parent_: options/base.yaml


arch:                                                       # architectural options
    resolution: [500,500]                                   # H , W of the svd grid, note that the order is different from planar_svd
    kernel_type: none                                       # kernel can be gaussian  , diff_gaussian or  average
    kernel_size: 21                                         # kerne width should be an odd integer
    # max_ranks = resolution // 5
c2f_schedule:                                                   # coarse-to-fine scheduling on positional encoding
    rank: [100]
    kernel_t: [12,0,0] 
tb:
    log_jacobian: false                                    #  log jacobian image with respect to each homgraphy parameter 

data:                                                       # data options
    image_fname: data/cat.jpg                               # path to image file
    image_size: [360,480]                                   # original image size
    patch_crop: [180,180]                                   # crop size of image patches to align

warp:                                                       # image warping options
    type: homography                                        # type of warp function
    dof: 8                                                  # degrees of freedom of the warp function
    #type: translation                                        # type of warp function
    #dof: 2                                                  # degrees of freedom of the warp function
    noise_h: 0.1                                            # scale of pre-generated warp perturbation (homography)
    noise_t: 0.2                                            # scale of pre-generated warp perturbation (translation)
    fix_first: true                                         # fix the first patch for uniqueness of solution

loss_weight:                                                # loss weights (in log scale)
    render: 0                                               # RGB rendering loss
    total_variance: -2

optim:                                                      # optimization options
    lr: 1.e-3                                              # learning rate (main)
    lr_warp: 1.e-2                                          # learning rate of warp parameters

batch_size: 5                                               # batch size (set to number of patches to consider)
max_iter: 15000                                              # train to maximum number of iterations

visdom:                                                     # Visdom options (turned off)

freq:                                                       # periodic actions during training
    scalar: 20                                              # log losses and scalar states (every N iterations)
    vis: 100                                                # visualize results (every N iterations)
